var wordIndex=[
    {word: "ISITCOOL.NET", value:100},
    {word: "ISITCOOL", value:100},
    {word: "COOL", value:100},
    {word: "COOLNESS", value:100}
];

var randomWordIndex=[
    /*Countries*/
    "United States",
    "India",
    "United Kingdom",
    "France",
    "Japan",
    "Germany",
    "Russia",
    "Philippines",
    "Australia",
    "Canada",
    "Spain",
    "England",
    "Singapore",
    "Italy",
    "South Korea",
    "North Korea",
    "Brazil",
    /*Food*/
    "Popcorn",
    "Chips",
    "Tacos",
    "Marzipan",
    "French Toast",
    "Burger",
    "Hot Dog",
    "Kebab",
    "Donuts",
    "Sushi",
    "Chocolate",
    "Curry",
    /*Sports*/
    "Football",
    "Tennis",
    "Soccer",
    "Baseball",
    "Bowling",
    "Golf",
    "Rugby",
    "Volleyball",
    "Hockey",
    "Basketball",
    "Cricket",
    /*Games*/
    "League of Legends",
    "Counter Strike",
    "Fallout 4",
    "Dota 2",
    "World of Warcraft",
    "World of Tanks",
    "Hearthstone",
    "Minecraft",
    "Grand Theft Auto",
    "Call of Duty",
    "Battlefield",
    "Borderlands",
    /*People*/
    "Justin Bieber",
    "Taylor Swift",
    "Ariana Grande",
    "Selena Gomez",
    "PewDiePie",
    "Bill Gates",
    "Steve Jobs",
    "Micheal Jackson",
    /*Characters*/
    "James Bond",
    /*Brands*/
    "VW",
    "Audi",
    "Porsche",
    "Lamborghini",
    "Apple",
    "Google",
    "Microsoft",
    "Coca Cola",
    "Facebook",
    "Toyota",
    "IBM",
    "Disney",
    "McDonalds",
    "Samsung",
    "Amazon",
    "BMW",
    /*Names*/
    "Michael",
    "Christopher",
    "Metthew",
    "Joshua",
    "Jacob",
    "Nicholas",
    "Andrew",
    "Daniel",
    "Tyler",
    "Joseph",
    "Brandon",
    "David",
    "James",
    /*Swag*/
    "#Swag",
    "#Yolo",
    /*Misc*/
    "Water",
    "Fire",
    "Tornado"
];
